# Generated by Django 3.2.15 on 2022-09-11 17:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_auto_20220422_1152"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapiruser",
            name="oidc_perms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
